### ISSUE TITLE
migrate to typescript-eslint v6

### ISSUE THREAD

**Issue by danielroe** [nuxt/eslint-config#298]
https://typescript-eslint.io/blog/announcing-typescript-eslint-v6/

**Comment by shinGangan** [comment]
Hey @danielroe .
If you don't have someone in charge, can I try?

I would like to proceed with the following policy.
- Enable `recommended` and `stylistic`, but only enable rules that are the same as the v5 recommended rules.
- Turn off rules added with `stylistic` so that they do not affect the roadmap.

I would also like to consider support for #303 and ESLint Flat Config, which will be supported in the future.
If there are no problems, I'd like to submit Pull Request ([experiment branch](https://github.com/shinGangan/eslint-config/tree/feat/migrate-typescript-eslint-v6)).

**Comment by danielroe** [comment]
@shinGangan I really appreciate it.

@DamianGlowala has been leading the work on this, so it might be worth waiting for his suggestion on the best way to contribute.

**Comment by shinGangan** [comment]
Hi @DamianGlowala  ( and @danielroe ).

I think that support for eslint-config is not a high priority for the Nuxt core team.
(Thanks for the release of Nuxt 3.9 and the development of many great features 🙏).

 However, many nuxt users are confused about eslint-config.

So, if I can help in any way, I would like to help it. It would be helpful if you could share your roadmap when you have time.
